# Generated by Django 6.1 on 2026-09-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
